In [1]:
from array import *
ar=array('i',[])
n= int(input('enter the value of array size'))
print(n)

enter the value of array size5
5


In [2]:
for f in range(n):
    j=int(input("enter"))
    ar.append(j)

enter56
enter25
enter78
enter65
enter15


In [3]:
ar

array('i', [56, 25, 78, 65, 15])

In [4]:
ar.pop(4)

15

In [7]:
arcopy=ar.copy()

AttributeError: 'array.array' object has no attribute 'copy'

In [99]:
ag=array([5,6,4,8,7,2])


In [100]:
print(ag)

[5 6 4 8 7 2]


In [101]:
#we use diffrent function for array
#copy array
sa=ag
sa

array([5, 6, 4, 8, 7, 2])

In [102]:
id(ag)

161289664

In [103]:
id(sa)

161289664

In [104]:
del sa

In [105]:
ag

array([5, 6, 4, 8, 7, 2])

In [107]:
sa=array([])
for x in ag:
    sa.append(x)
sa

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [1]:
tu=('apple','purple','pappaya')
print(type(tu))

<class 'tuple'>


In [4]:
print(tu)
if 'papple' in tu:
    print('yes')
else :
    print('no')

('apple', 'purple', 'pappaya')
no


In [5]:
set1={'set1','set2','set3','set4'}

In [7]:
print(set1)
set1.pop()
print(set1)

{'set4', 'set1', 'set3', 'set2'}
{'set1', 'set3', 'set2'}


AttributeError: 'set' object has no attribute 'short'

In [6]:
x=int(input('enter 1st'))
y=int(input('enter 2nd'))
      
def add_sub(x,y):
      return x+y,x-y;
r1,r2=add_sub(8,5)
print(r1+r2)

enter 1st5
enter 2nd5
16
